name: Convert PDF to DOCX

on:
  workflow_dispatch:
    inputs:
      pdf_path:
        description: 'Path to PDF file in the repository (relative to repo root)'
        required: true
        default: 'پیش نویس نامه مدیریت.pdf'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install system packages
      run: |
        sudo apt-get update
        sudo apt-get install -y poppler-utils tesseract-ocr tesseract-ocr-fas libtesseract-dev libreoffice

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install ocrmypdf pdf2docx

    - name: Run conversion script
      env:
        PDF_PATH: ${{ github.event.inputs.pdf_path }}
      run: |
        mkdir -p converted
        python3 scripts/convert_pdf_to_docx.py "$PDF_PATH" converted

    - name: Upload results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: converted-docx
        path: converted/*.docx